export default function CreditsPage() {
    return (<main className="bg-neutral-50 min-h-screen">
        {/* Hero */} <section className="max-w-4xl mx-auto px-6 pt-16 pb-10"> <div className="mb-6"> <p className="text-[11px] uppercase tracking-[0.25em] text-amber-600 font-semibold">
            Transparency </p> <h1 className="mt-2 text-3xl sm:text-4xl font-serif text-neutral-900">
                Media & Resource Credits </h1> <p className="mt-3 text-neutral-600 max-w-2xl text-sm leading-relaxed">
                We gratefully acknowledge the creators and platforms that provided
                the images, videos, icons, and resources used across our website. </p> </div> </section>

        ```
        <section className="max-w-4xl mx-auto px-6 pb-20 space-y-10">

            <CreditSection
                title="Videos"
                items={[
                    {
                        name: "Pexels",
                        description: "High-quality Video used across hero sections.",
                        link: "https://www.pexels.com/video/two-schoolboys-writing-on-desk-in-classroom-11025407/",
                    },
                ]}
            />

            {/* Videos */}
            <CreditSection
                title="Images"
                items={[
                    {
                        name: "Principal Image",
                        description: "Generated by Google Gemini",
                        link: "https://gemini.google.com/app?hl=en-IN",
                    },
                    {
                        name: "classroom",
                        description: "Image of classroom",
                        link: "https://pin.it/10itd0upV",
                    },
                    {
                        name: "Science Laboratory",
                        description: "Image of Laboratory",
                        link: "https://pin.it/46RQdQ2tR",
                    },
                    {
                        name: "Library",
                        description: "Image of Library",
                        link: "https://pin.it/4UakF7Rq7",
                    },
                    {
                        name: "Computer Lab",
                        description: "Image of Computer lab",
                        link: "https://pin.it/YIaH9RTcz",
                    },
                    {
                        name: "Sports Facilities",
                        description: "Image of Sports Ground used across admission and Facilities Section",
                        link: "https://pin.it/2ifoRwZ8K",
                    },
                    {
                        name: "Sports Events victory",
                        description: "Image of Sport Event Victory",
                        link: "https://pin.it/2Reg81Ww9",
                    },
                    {
                        name: "Annual Function",
                        description: "Image of Annual Function",
                        link: "https://pin.it/oevTLr2se",
                    },
                    {
                        name: "Graduation Day",
                        description: "Image of Graduation Day",
                        link: "https://pin.it/2NH41ETO4",
                    },
                ]}
            />
        </section>
    </main>


    )
}

function CreditSection({
    title,
    items,
}: {
    title: string
    items: { name: string; description: string; link: string }[]
}) {
    return (<div> <h2 className="text-lg font-semibold text-neutral-900 mb-4 border-b border-neutral-200 pb-2">
        {title} </h2>


        <div className="grid sm:grid-cols-2 gap-4">
            {items.map((item) => (
                <div
                    key={item.name}
                    className="bg-white border border-neutral-200 rounded-lg p-4 hover:border-amber-300 transition"
                >
                    <h3 className="text-sm font-medium text-neutral-900">
                        {item.name}
                    </h3>

                    <p className="text-xs text-neutral-600 mt-1 leading-relaxed">
                        {item.description}
                    </p>

                    <a
                        href={item.link}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-block mt-2 text-xs font-medium text-amber-600 hover:text-amber-700 transition"
                    >
                        Visit source →
                    </a>
                </div>
            ))}
        </div>
    </div>


    )
}
